"""Interactive Streamlit dashboard for the Madrid Air Quality project.

This application presents the main results of the analysis pipeline through
task-specific pages, summary metrics, saved figures, interactive tables, and
network maps.

The dashboard:
- summarizes the full project pipeline,
- displays outputs from Tasks 1–10,
- reads saved CSV tables and figure files from the `outputs/` directory,
- provides interactive views for spatial and correlation networks,
- presents final forecasting and parallelization results in a presentation-ready format.
"""
# streamlit app framework
import streamlit as st

# tabular data handling
import pandas as pd

# filesystem paths and saved figure loading
from pathlib import Path
import matplotlib.image as mpimg

# interactive mapping and coordinate conversion
import pydeck as pdk
from pyproj import Transformer

# graph file loading for network overlays
import networkx as nx

# interactive charts
import plotly.express as px
import plotly.graph_objects as go

# configure the dashboard layout before rendering any page content
st.set_page_config(
    page_title="Madrid Air Quality",
    layout="wide",
    initial_sidebar_state="expanded",
)

# CSS customization: custom dark-theme styling for the app, metric cards, tabs, and pipeline cards
st.markdown("""
<style>
    /* Main background — dark */
    .stApp { background-color: #0e1117; color: #fafafa; }
    .main .block-container { background-color: #0e1117; }

    /* Metric cards */
    [data-testid="stMetric"] {
        background: #1e2130;
        border-radius: 12px;
        padding: 16px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.3);
        border-left: 4px solid #6c63ff;
    }
    [data-testid="stMetricLabel"] { color: #d4d0ff !important; font-weight: 600; font-size: 0.85em; }
    [data-testid="stMetricValue"] { color: #ffffff !important; font-size: 1.1em !important; }
    [data-testid="stMetricDelta"] { font-size: 0.75em !important; }

    /* Tab styling */
    .stTabs [data-baseweb="tab"] {
        background: #1e2130;
        border-radius: 8px 8px 0 0;
        color: #a29bfe;
        font-weight: 600;
    }
    .stTabs [aria-selected="true"] {
        background: #6c63ff !important;
        color: white !important;
    }

    /* Cards for pipeline */
    .pipeline-card {
        background: #1e2130;
        border-radius: 10px;
        padding: 12px;
        text-align: center;
        box-shadow: 0 2px 6px rgba(0,0,0,0.3);
        border-top: 3px solid #6c63ff;
        color: #fafafa;
    }
</style>
""", unsafe_allow_html=True)

# root folder containing task outputs generated by the analysis pipeline
OUTPUTS = Path("outputs")

def task_tables(task): 
    """return the saved tables folder for a given task."""

    return OUTPUTS / task / "tables"
def task_figures(task): 
    """return the saved figures folder for a given task."""

    return OUTPUTS / task / "figures"

def safe_read(path, **kwargs):
    """read a csv table if it exists, otherwise return an empty dataframe."""
    if Path(path).exists():
        return pd.read_csv(path, **kwargs)
    return pd.DataFrame()

def safe_img(path):
    """load a saved image if it exists, otherwise return none."""
    p = Path(path)
    if p.exists():
        return mpimg.imread(str(p))
    return None

def show_img(path, caption="", use_container_width=True):
    """display a saved figure or warn the user when the file is unavailable."""

    img = safe_img(path)
    if img is not None:
        st.image(img, caption=caption, use_container_width=use_container_width)
    else:
        st.warning(f"Figure not found: {Path(path).name}")

# sidebar navigation, branding, and presentation-level headline findings
st.sidebar.image(
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzhubnBidGhiNXNrNDZjMTlxeG40NDFxYnY2b2x3c281OGhoM2cybiZlcD12MV9zdGlja2Vyc19zZWFyY2gmY3Q9cw/VreD0cdnIJyvRNCnuU/giphy.gif",
    width=300
)
st.sidebar.title("Madrid Air Quality")
st.sidebar.caption("Kungfu Pandas — Madrid Air Quality")
st.sidebar.markdown("---")

# choose which task page to display
page = st.sidebar.radio(
    "Navigate",
    [
        " Overview",
        " Task 1 — Load & Inspect",
        " Task 2 — Missingness",
        " Task 3 — Imputation",
        " Task 4 — Temporal Analysis",
        " Task 5 — Spatial Network",
        " Task 6 — Correlation Network",
        " Task 8 — Parallelization",
        " Task 9 — Forecasting",
        " Task 10 — Final Visualization",
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown("**Key Findings**")
st.sidebar.markdown(" NO₂ ↓ declining since 2001")
st.sidebar.markdown(" O₃ ↑ only pollutant rising")
st.sidebar.markdown(" Wind speed = top pollution reducer")
st.sidebar.markdown(" 3.17× speedup with 6 workers")
st.sidebar.markdown(" Gradient Boosting R²=0.67")


# overview page: project scale, dataset composition, and headline findings
if page == " Overview":
    st.title("🌬️ Madrid Air Quality Analysis")
    st.markdown("**A complete analytics pipeline — 64.6M rows · 24 sensors · 2001–2024**")

    # display project-wide summary metrics
    col1, col2, col3, col4, col5, col6 = st.columns(6)
    col1.metric("Total Rows", "64.6M")
    col2.metric("Sensors", "24")
    col3.metric("Variables", "36")
    col4.metric("Years", "24")
    col5.metric("Pollutants", "14")
    col6.metric("Tasks", "10")

    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Dataset Composition")
        fig = go.Figure(data=[go.Pie(
            labels=["Traffic", "Pollutant", "Weather"],
            values=[30.4, 25.5, 8.8],
            hole=0.45,
            marker_colors=["#ff7f0e", "#1f77b4", "#61b861"],
            textinfo="label+percent",
        )])
        fig.update_layout(
            showlegend=True,
            height=300,
            margin=dict(t=10, b=10, l=10, r=10),
            paper_bgcolor="#0e1117",
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Original Missingness by Variable Type")
        fig2 = go.Figure(go.Bar(
            x=["Pollutant", "Weather", "Traffic"],
            y=[2.5, 75.4, 0.0],
            marker_color=["#1f77b4", "#61b861", "#ff7f0e"],
            text=["2.5%", "75.4%", "0.0%"],
            textposition="outside",
        ))
        fig2.update_layout(
            yaxis_title="Missingness (%)",
            height=300,
            margin=dict(t=10, b=10, l=10, r=10),
            paper_bgcolor="#0e1117",
            plot_bgcolor="#0e1117",
        )
        st.plotly_chart(fig2, use_container_width=True)

    st.markdown("---")
    st.subheader("Analytics Pipeline")
    cols = st.columns(9)
    tasks = ["Load & Inspect", "Missingness", "Imputation", "Temporal Analysis", "Spatial Network",
             "Correlation Network", "Parallelization", "Forecasting", "Final Visualization"]
    colors = ["#6c63ff","#6c63ff","#6c63ff","#6c63ff","#6c63ff","#6c63ff","#6c63ff","#6c63ff","#6c63ff"]
    for col, task, color in zip(cols, tasks, colors):
        col.markdown(
            f'<div class="pipeline-card" style="border-top-color:{color};height:110px;width:100px;display:flex;flex-direction:column;justify-content:center;align-items:center">'
            f'<div style="font-size:0.75em;color:#ffffff;font-weight:600;margin-top:4px;text-align:center">{task}</div>'
            f'</div>',
            unsafe_allow_html=True
        )

    st.markdown("---")
    st.subheader("Inverse & Positive Relationships Found")
    col1, col2 = st.columns(2)
    with col1:
        st.error("**Inverse Relationships**\n\n↑ NO2 ↓ O3\n\n↑ Wind Speed ↓ NO2\n\n↑ Temperature ↓ NO2")
    with col2:
        st.success("**Positive Relationships**\n\n↑ Traffic ↑ NO2\n\n↑ Solar Radiation ↑ O3\n\n↑ NO ↑ NOX")

# task 1 — loading and initial inspection
elif page == " Task 1 — Load & Inspect":
    st.title(" Task 1 — Load & Inspect")
    st.markdown("**Goal:** Understand schema, scale, and time coverage of the METRAQ dataset.")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Rows", "64.6M")
    col2.metric("Time Span", "2001–2024")
    col3.metric("Sensors", "24")
    col4.metric("Variables", "36")

    st.markdown("---")

    tab1, tab2 = st.tabs([" Figures", " Dataset Info"])

    with tab1:
        fig_choice = st.selectbox("Select figure", [
            "Variable type counts",
            "Interpolation rate by variable type",
            "NO monthly time series",
            "NO value distribution",
        ])
        fname_map = {
            "Variable type counts": "variable_type_counts.png",
            "Interpolation rate by variable type": "interpolation_rate_by_variable_type.png",
            "NO monthly time series": "NO_monthly_timeseries.png",
            "NO value distribution": "NO_value_distribution.png",
        }
        show_img(task_figures("task1_load_inspect") / fname_map[fig_choice], fig_choice)

    with tab2:
        data = {"Variable type": ["Traffic", "Pollutant", "Weather"],
                "Rows (M)": [30.4, 25.5, 8.8],
                "Share": ["47%", "39%", "14%"]}
        st.dataframe(pd.DataFrame(data), use_container_width=True, hide_index=True)
        st.info("NO was auto-selected as example pollutant — highest row count in dataset.")

# task 2 - missingness
elif page == " Task 2 — Missingness":
    st.title(" Data Quality & Missingness")

    col1, col2, col3 = st.columns(3)
    col1.metric("Real observed", "88.8%", "is_interpolated = False")
    col2.metric("Missing (filled by METRAQ)", "11.2%")
    col3.metric("Invalid values", "0.002%", "684 negative + 771 humidity OOR")

    st.markdown("---")
    tab1, tab2, tab3 = st.tabs([" Figures", " Missingness Tables", " Invalid Values"])

    with tab1:
        figure_choice = st.selectbox("Select figure", [
            "Data Quality Dashboard",
            "Sensor × Pollutant Heatmap",
            "Data Availability Matrix",
            "Missingness Over Time (Stacked)",
            "Gap Length Distribution",
        ])
        fname_map = {
            "Data Quality Dashboard": "data_quality_dashboard.png",
            "Sensor × Pollutant Heatmap": "missingness_heatmap_sensor_variable.png",
            "Data Availability Matrix": "data_availability_matrix.png",
            "Missingness Over Time (Stacked)": "missingness_by_year_type_stacked.png",
            "Gap Length Distribution": "gap_length_distribution.png",
        }
        show_img(task_figures("task2_missingness") / fname_map[figure_choice], figure_choice)

        st.info("""
        **Key finding:** Weather data is 75.4% missing (introduced 2019), 
        pollutants only 2.5%, traffic 0%. Missing gaps can be multi-year for some sensors.
        """)

    with tab2:
        view = st.radio("View by", ["Pollutant", "Sensor", "Variable type"], horizontal=True)
        if view == "Pollutant":
            df = safe_read(task_tables("task2_missingness") / "original_missingness_by_pollutant.csv")
        elif view == "Sensor":
            df = safe_read(task_tables("task2_missingness") / "original_missingness_by_sensor.csv")
        else:
            df = safe_read(task_tables("task2_missingness") / "original_missingness_by_variable_type.csv")

        if not df.empty:
            if "original_missing_rate" in df.columns:
                df["original_missing_rate"] = df["original_missing_rate"].map("{:.2%}".format)
            st.dataframe(df, use_container_width=True, hide_index=True)

    with tab3:
        df = safe_read(task_tables("task2_missingness") / "invalid_values_summary.csv")
        if not df.empty:
            st.dataframe(df, use_container_width=True, hide_index=True)
        st.warning("Invalid values exist even where is_interpolated = False — real measurements can still be erroneous.")


#  task 3: imputation
elif page == " Task 3 — Imputation":
    st.title(" Imputation Methods")
    st.markdown("We reconstruct original missingness using `is_interpolated == True`, then apply 5 methods and compare against METRAQ's spatial interpolation.")

    col1, col2, col3 = st.columns(3)
    col1.metric("Missing values imputed", "7.2M")
    col2.metric("Best method (MAE)", "Last-next avg — 45.8")
    col3.metric("Worst method (MAE)", "Forward fill — 197.1")

    st.markdown("---")

    tab1, tab2, tab3 = st.tabs([" Method Ranking", " Distribution Overlays", " Error Tables"])

    with tab1:
        col1, col2 = st.columns([1.2, 1])
        with col1:
            show_img(task_figures("task3_imputation") / "imputation_method_ranking.png",
                     "Method ranking by MAE vs METRAQ")
        with col2:
            st.markdown("**Methods Tested**")
            methods = {
                "Last-next avg": (" Best:", "Average of last known before + first known after gap"),
                "Grouped median": (" Good:", "Median for that sensor/variable — robust to outliers"),
                "Grouped mean": (" OK:", "Mean for that sensor/variable — sensitive to outliers"),
                "Backward fill": (" Poor:", "Repeats next known value — fails on long gaps"),
                "Forward fill": (" Poor:", "Repeats last known value — fails on long gaps"),
            }
            for method, (badge, desc) in methods.items():
                st.markdown(f"**{badge} {method}**")
                st.caption(desc)
                st.markdown("")

            st.info("MAE measured vs METRAQ interpolation — relative comparison only, not absolute accuracy.")

    with tab2:
        pollutant = st.selectbox("Select pollutant", ["NO2", "NOX", "NO", "O3", "CO", "SO2", "PM10", "PM2_5"])
        show_img(task_figures("task3_imputation") / f"distribution_overlay_pollutant_{pollutant}.png",
                 f"Distribution overlay — {pollutant}")
        st.caption("Black line = real observed distribution. A good method should match it closely. "
                   "Fill methods preserve tails better; statistical methods preserve overall shape better. "
                   "No method fully captures extreme values.")

    with tab3:
        df = safe_read(task_tables("task3_imputation") / "imputation_error_summary.csv")
        if not df.empty:
            display_cols = ["method_label", "mae_vs_metraq", "rmse_vs_metraq", "median_error", "mean_error"]
            available = [c for c in display_cols if c in df.columns]
            st.dataframe(df[available].round(3), use_container_width=True, hide_index=True)

        show_img(task_figures("task3_imputation") / "imputation_method_comparison_panel.png",
                 "Full comparison panel")


# task 3: temporal analysis
elif page == " Task 4 — Temporal Analysis":
    st.title(" Temporal Analysis")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("NO2 trend", "−0.118 µg/m³/month", "Mann-Kendall p<0.001")
    col2.metric("NOX trend", "−0.286 µg/m³/month", "Mann-Kendall p<0.001")
    col3.metric("O3 trend", "+0.066 µg/m³/month", "Only pollutant rising")
    col4.metric("COVID NO2 drop", "−24.6%", "2020 lockdown")

    st.markdown("---")

    tab1, tab2, tab3, tab4 = st.tabs([" Long-term Trends", " Cycles", " Mann-Kendall", " Tables"])

    with tab1:
        trend_fig = st.selectbox("Select figure", [
            "Long-term trend with COVID annotation",
            "Yearly pollution trends",
            "NO2 vs O3 anticorrelation (seasonal)",
            "Station-year heatmap (NO)",
        ])
        fname_map = {
            "Long-term trend with COVID annotation": "longterm_trend_covid_annotated.png",
            "Yearly pollution trends": "yearly_pollution_trends.png",
            "NO2 vs O3 anticorrelation (seasonal)": "no2_o3_anticorrelation_seasonal.png",
            "Station-year heatmap (NO)": "station_year_heatmap_NO.png",
        }
        show_img(task_figures("task4_temporal") / fname_map[trend_fig], trend_fig)

    with tab2:
        cycle_type = st.radio("Cycle type", ["Hourly", "Daily (weekday)", "Seasonal (monthly)"], horizontal=True)
        fname_map2 = {
            "Hourly": "hourly_pollution_cycle.png",
            "Daily (weekday)": "weekday_pollution_cycle.png",
            "Seasonal (monthly)": "seasonal_pollution_cycle.png",
        }
        show_img(task_figures("task4_temporal") / fname_map2[cycle_type], cycle_type)

        if cycle_type == "Hourly":
            st.info("NOX peaks at 8am (morning rush) and 8-9pm (evening rush). O3 peaks midday when UV is highest.")
        elif cycle_type == "Daily (weekday)":
            st.info("NO/NOX significantly lower on weekends — confirms traffic as primary source.")
        else:
            st.info("NO2/NOX peak in winter (low UV, cold air trapping). O3 peaks in summer (photochemical production).")

    with tab3:
        df = safe_read(task_tables("task4_temporal") / "mann_kendall_trend_summary.csv")
        if not df.empty:
            fig = go.Figure()
            colors = ["#2ecc71" if t == "decreasing" else "#e74c3c" 
                      for t in df["trend_direction"]]
            fig.add_trace(go.Bar(
                x=df["magnitude_name"],
                y=df["mk_tau"],
                marker_color=colors,
                text=df["mk_tau"].round(3),
                textposition="outside",
            ))
            fig.update_layout(
                title="Mann-Kendall Tau per Pollutant (negative = improving)",
                yaxis_title="Tau",
                height=400,
                paper_bgcolor="#0e1117",
                plot_bgcolor="#0e1117",
            )
            fig.add_hline(y=0, line_color="black", line_width=1)
            st.plotly_chart(fig, use_container_width=True)

            col1, col2 = st.columns(2)
            decreasing = df[df["trend_direction"] == "decreasing"]["magnitude_name"].tolist()
            increasing = df[df["trend_direction"] == "increasing"]["magnitude_name"].tolist()
            col1.success(f"**Improving:** {', '.join(decreasing)}")
            col2.error(f"**Worsening:** {', '.join(increasing)}")

        show_img(task_figures("task4_temporal") / "acf_lag12_by_pollutant.png",
                 "Annual seasonality strength (ACF lag-12)")

    with tab4:
        df = safe_read(task_tables("task4_temporal") / "temporal_interpretation_summary.csv")
        if not df.empty:
            st.dataframe(df.round(4), use_container_width=True, hide_index=True)


#  task: spatial network
elif page == " Task 5 — Spatial Network":
    st.title(" Spatial Network")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Nodes", "24", "sensors")
    col2.metric("Edges (kNN k=2)", "32")
    col3.metric("Communities", "5", "Louvain modularity")
    col4.metric("Top bridge", "Ramón y Cajal", "betweenness 0.577")

    st.markdown("---")

    # interactive controls
    col1, col2 = st.columns([1, 2])
    with col1:
        graph_type = st.radio("Connection method", ["KNN", "Distance threshold"], horizontal=False)
        if graph_type == "KNN":
            k_val = st.select_slider("k (nearest neighbours)", options=[2, 3, 4, 5], value=2)
            graph_key = f"knn_k{k_val}"
            graphml_path = OUTPUTS / "task5_spatial_network" / "graphs" / f"knn_k{k_val}.graphml"
        else:
            dist_val = st.select_slider("Distance threshold", options=["3024m", "4709m", "7517m", "10452m"])
            graph_key = f"threshold_{dist_val}"
            graphml_path = OUTPUTS / "task5_spatial_network" / "graphs" / f"threshold_{dist_val}.graphml"

        df_summary = safe_read(task_tables("task5_spatial_network") / "spatial_graph_summary.csv")
        if not df_summary.empty:
            row = df_summary[df_summary["graph_name"] == graph_key]
            if not row.empty:
                st.markdown("**Graph stats:**")
                st.markdown(f"- Edges: **{int(row['n_edges'].iloc[0])}**")
                st.markdown(f"- Density: **{row['density'].iloc[0]:.3f}**")
                st.markdown(f"- Connected: **{row['is_connected'].iloc[0]}**")
                st.markdown(f"- Components: **{int(row['n_connected_components'].iloc[0])}**")

    with col2:
        # interactive map 
        coords = safe_read(task_tables("task5_spatial_network") / "sensor_coordinates.csv")
        centrality = safe_read(task_tables("task5_spatial_network") / "spatial_node_centrality.csv")

        if not coords.empty:
            try:
                transformer = Transformer.from_crs("EPSG:32630", "EPSG:4326", always_xy=True)
                coords["lon"], coords["lat"] = transformer.transform(
                    coords["utm_x"].values, coords["utm_y"].values
                )

                # merge centrality for node sizing
                if not centrality.empty:
                    cent_k = centrality[centrality["graph_name"] == graph_key]
                    if not cent_k.empty:
                        coords = coords.merge(
                            cent_k[["sensor_id", "betweenness_centrality"]],
                            on="sensor_id", how="left"
                        )
                        coords["radius"] = (
                            300 + coords["betweenness_centrality"].fillna(0) * 1000
                        ).clip(300, 1200)
                    else:
                        coords["radius"] = 400
                else:
                    coords["radius"] = 400

                # community colors
                community_colors = [
                    [108, 99, 255, 200],   # purple
                    [255, 107, 107, 200],  # red
                    [46, 204, 113, 200],   # green
                    [52, 152, 219, 200],   # blue
                    [243, 156, 18, 200],   # orange
                ]
                coords["color"] = [[108, 99, 255, 200]] * len(coords)

                sensor_layer = pdk.Layer(
                    "ScatterplotLayer",
                    data=coords,
                    get_position=["lon", "lat"],
                    get_fill_color="color",
                    get_radius="radius",
                    pickable=True,
                )
                text_layer = pdk.Layer(
                    "TextLayer",
                    data=coords,
                    get_position=["lon", "lat"],
                    get_text="sensor_name",
                    get_size=11,
                    get_color=[30, 30, 30, 200],
                    get_pixel_offset=[0, -15],
                )

                layers = []
                if graphml_path.exists():
                    G = nx.read_graphml(str(graphml_path))
                    edges = []
                    for u, v in G.edges():
                        u_row = coords[coords["sensor_id"].astype(str) == str(u)]
                        v_row = coords[coords["sensor_id"].astype(str) == str(v)]
                        if not u_row.empty and not v_row.empty:
                            edges.append({
                                "source_lon": float(u_row["lon"].iloc[0]),
                                "source_lat": float(u_row["lat"].iloc[0]),
                                "target_lon": float(v_row["lon"].iloc[0]),
                                "target_lat": float(v_row["lat"].iloc[0]),
                            })
                    if edges:
                        edge_layer = pdk.Layer(
                            "LineLayer",
                            data=pd.DataFrame(edges),
                            get_source_position=["source_lon", "source_lat"],
                            get_target_position=["target_lon", "target_lat"],
                            get_color=[108, 99, 255, 160],
                            get_width=2,
                        )
                        layers.append(edge_layer)

                layers += [sensor_layer, text_layer]
                st.pydeck_chart(pdk.Deck(
                    layers=layers,
                    initial_view_state=pdk.ViewState(latitude=40.42, longitude=-3.70, zoom=10),
                    tooltip={"text": "{sensor_name}"},
                    map_style="light",
                ))
                st.caption("Node size = betweenness centrality. Larger = more bridge-like.")
            except Exception as e:
                st.warning(f"Map could not load: {e}")

    st.markdown("---")
    tab1, tab2, tab3 = st.tabs([" Network Figures", " Comparison", " Centrality Table"])

    with tab1:
        fig_choice = st.selectbox("Select figure", [
            "Community & betweenness — kNN k=2",
            "Pollution level & eigenvector — kNN k=2",
            "Centrality ranking — kNN k=2",
            "Community — kNN k=3",
            "Community — kNN k=4",
            "Community — kNN k=5",
            "Community — threshold 3024m",
            "Community — threshold 4709m",
            "Community — threshold 7517m",
            "Community — threshold 10452m",
        ])
        fname_map = {
            "Community & betweenness — kNN k=2": "spatial_network_knn_k2_community_centrality.png",
            "Pollution level & eigenvector — kNN k=2": "spatial_network_knn_k2_pollution_eigenvector.png",
            "Centrality ranking — kNN k=2": "centrality_ranking_knn_k2.png",
            "Community — kNN k=3": "spatial_network_knn_k3_community_centrality.png",
            "Community — kNN k=4": "spatial_network_knn_k4_community_centrality.png",
            "Community — kNN k=5": "spatial_network_knn_k5_community_centrality.png",
            "Community — threshold 3024m": "spatial_network_threshold_3024m_community_centrality.png",
            "Community — threshold 4709m": "spatial_network_threshold_4709m_community_centrality.png",
            "Community — threshold 7517m": "spatial_network_threshold_7517m_community_centrality.png",
            "Community — threshold 10452m": "spatial_network_threshold_10452m_community_centrality.png",
        }
        show_img(task_figures("task5_spatial_network") / fname_map[fig_choice], fig_choice)

    with tab2:
        metric = st.radio("Metric", ["density", "average_degree", "n_connected_components"], horizontal=True)
        show_img(task_figures("task5_spatial_network") / f"network_{metric}_comparison.png", metric)

    with tab3:
        df = safe_read(task_tables("task5_spatial_network") / "selected_spatial_node_centrality.csv")
        if not df.empty:
            top = df.nlargest(10, "betweenness_centrality")
            fig = px.bar(
                top.sort_values("betweenness_centrality"),
                x="betweenness_centrality",
                y="sensor_name",
                orientation="h",
                color="betweenness_centrality",
                color_continuous_scale="Purples",
                title="Top sensors by betweenness centrality",
            )
            fig.update_layout(height=400, paper_bgcolor="#0e1117", plot_bgcolor="#0e1117")
            st.plotly_chart(fig, use_container_width=True)
            st.dataframe(df.round(4), use_container_width=True, hide_index=True)

# task 6:correlation network
elif page == " Task 6 — Correlation Network":
    st.title(" Correlation Network")
    st.markdown("Sensors connected by **behavioural similarity** in pollutant time series — not geographic proximity.")

    col1, col2, col3 = st.columns(3)
    col1.metric("Shared edges (spatial ∩ corr)", "32", "at r≥0.60")
    col2.metric("Correlation-only edges", "244", "not captured by distance")
    col3.metric("Jaccard similarity", "0.116", "spatial vs correlation")

    st.markdown("---")

    # interactive map 
    st.subheader("Interactive Network Map")
    coords = safe_read(task_tables("task5_spatial_network") / "sensor_coordinates.csv")

    if not coords.empty:
        try:
            transformer = Transformer.from_crs("EPSG:32630", "EPSG:4326", always_xy=True)
            coords["lon"], coords["lat"] = transformer.transform(
                coords["utm_x"].values, coords["utm_y"].values
            )

            col1, col2, col3 = st.columns(3)
            with col1:
                show_spatial = st.checkbox(" Spatial (kNN k=2)", value=True)
            with col2:
                corr_pollutant = st.selectbox("Correlation pollutant", ["NO2", "NO", "NOX", "O3", "<PM10"])
                corr_threshold = st.select_slider("Threshold", options=[0.50, 0.60, 0.70, 0.80, 0.90], value=0.60)
                show_corr = st.checkbox("Show correlation edges", value=True)

            def load_edges(path, color):
                if not Path(path).exists():
                    return pd.DataFrame()
                G = nx.read_graphml(str(path))
                edges = []
                for u, v in G.edges():
                    u_row = coords[coords["sensor_id"].astype(str) == str(u)]
                    v_row = coords[coords["sensor_id"].astype(str) == str(v)]
                    if not u_row.empty and not v_row.empty:
                        edges.append({
                            "source_lon": float(u_row["lon"].iloc[0]),
                            "source_lat": float(u_row["lat"].iloc[0]),
                            "target_lon": float(v_row["lon"].iloc[0]),
                            "target_lat": float(v_row["lat"].iloc[0]),
                            "color": color,
                        })
                return pd.DataFrame(edges)

            layers = []

            if show_spatial:
                sp_edges = load_edges(
                    OUTPUTS / "task5_spatial_network" / "graphs" / "selected_knn_k2.graphml",
                    [100, 100, 255, 180]
                )
                if not sp_edges.empty:
                    layers.append(pdk.Layer("LineLayer", data=sp_edges,
                        get_source_position=["source_lon", "source_lat"],
                        get_target_position=["target_lon", "target_lat"],
                        get_color=[100, 100, 255, 180], get_width=2))

            if show_corr:
                fname = f"correlation_network_{corr_pollutant}_corr_{corr_threshold:.2f}.graphml"
                corr_edges = load_edges(
                    OUTPUTS / "task6_correlation_network" / "graphs" / fname,
                    [220, 50, 50, 150]
                )
                if not corr_edges.empty:
                    layers.append(pdk.Layer("LineLayer", data=corr_edges,
                        get_source_position=["source_lon", "source_lat"],
                        get_target_position=["target_lon", "target_lat"],
                        get_color=[220, 50, 50, 150], get_width=2))

            sensor_layer = pdk.Layer("ScatterplotLayer", data=coords,
                get_position=["lon", "lat"],
                get_fill_color=[50, 50, 80, 220], get_radius=350, pickable=True)
            text_layer = pdk.Layer("TextLayer", data=coords,
                get_position=["lon", "lat"], get_text="sensor_name",
                get_size=11, get_color=[0, 0, 0, 180], get_pixel_offset=[0, -12])

            layers += [sensor_layer, text_layer]
            st.pydeck_chart(pdk.Deck(
                layers=layers,
                initial_view_state=pdk.ViewState(latitude=40.42, longitude=-3.70, zoom=10),
                tooltip={"text": "{sensor_name}"},
                map_style="light",
            ))

            leg_col1, leg_col2 = st.columns(2)
            if show_spatial:
                leg_col1.markdown(" **Spatial** — geographic proximity (kNN k=2)")
            if show_corr:
                leg_col2.markdown(f" **{corr_pollutant} r≥{corr_threshold}** — behavioural similarity")

        except Exception as e:
            st.warning(f"Map could not load: {e}")

    st.markdown("---")

    tab1, tab2, tab3, tab4 = st.tabs([" Network Figures", " Cross-pollutant", " Joint Overlay", " Jaccard"])

    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            pollutant = st.selectbox("Pollutant", ["NO2", "NO", "NOX", "O3", "<PM10"])
        with col2:
            threshold = st.select_slider("Correlation threshold", options=[0.50, 0.60, 0.70, 0.80, 0.90])

        fname = f"correlation_network_{pollutant}_corr_{threshold:.2f}.png"
        show_img(task_figures("task6_correlation_network") / fname,
                 f"{pollutant} correlation network at r≥{threshold}")

        show_img(task_figures("task6_correlation_network") / f"centrality_ranking_{pollutant}_corr_0.50.png",
                 f"Centrality ranking — {pollutant}")

    with tab2:
        metric2 = st.radio("Metric", ["density", "average_degree", "n_edges"], horizontal=True)
        show_img(task_figures("task6_correlation_network") / f"cross_pollutant_{metric2}.png", metric2)

    with tab3:
        show_img(task_figures("task6_correlation_network") / "joint_spatial_correlation_overlay.png",
                 "Spatial vs correlation overlay")
        df = safe_read(task_tables("task6_correlation_network") / "joint_network_overlay_summary.csv")
        if not df.empty:
            st.dataframe(df, use_container_width=True, hide_index=True)

    with tab4:
        show_img(task_figures("task6_correlation_network") / "community_jaccard_similarity.png",
                 "Community agreement")
        df = safe_read(task_tables("task6_correlation_network") / "community_jaccard_similarity.csv")
        if not df.empty:
            st.dataframe(df, use_container_width=True, hide_index=True)


# task 8: parallelization
elif page == " Task 8 — Parallelization":
    st.title(" Parallelization — Task 8")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Sequential", "21.4s")
    col2.metric("Parallel (6 workers)", "6.8s")
    col3.metric("Speedup", "3.17×", "vs theoretical 6×")
    col4.metric("Tasks computed", "576", "24 sensors × 24 years")

    st.info("Each worker independently reads only its year/sensor subset via parquet column pruning. "
            "Gap from theoretical 6× = Amdahl's Law — serial I/O becomes the bottleneck.")

    tab1, tab2, tab3, tab4 = st.tabs([" Runtime & Speedup", " Stable Pairs", " Pollution Drivers", " Tables"])

    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            # interactive plotly version of runtime comparison
            fig = go.Figure(go.Bar(
                x=["Sequential", "Parallel\n(6 workers)"],
                y=[21.4, 6.8],
                marker_color=["#4C72B0", "#55A868"],
                text=["21.4s", "6.8s"],
                textposition="outside",
                textfont=dict(size=14, color="white"),
                width=0.4,
            ))
            fig.update_layout(
                title="Sequential vs Parallel Runtime — 3.17× speedup",
                yaxis_title="Wall-clock time (s)",
                yaxis=dict(range=[0, 28]),
                height=380,
                paper_bgcolor="#0e1117",
                plot_bgcolor="#0e1117",
                font=dict(color="white"),
            )
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            # interactive speedup curve
            df_speedup = safe_read(task_tables("task8_parallelization") / "speedup_curve.csv")
            if not df_speedup.empty:
                par = df_speedup[df_speedup["mode"] == "parallel"]
                max_w = par["n_workers"].max()
                fig2 = go.Figure()
                fig2.add_trace(go.Scatter(
                    x=par["n_workers"], y=par["speedup"],
                    mode="lines+markers+text",
                    name="Observed speedup",
                    marker=dict(size=10, color="#55A868"),
                    line=dict(width=2.5, color="#55A868"),
                    text=par["speedup"].round(2).astype(str) + "×",
                    textposition="top center",
                ))
                fig2.add_trace(go.Scatter(
                    x=[1, max_w], y=[1, max_w],
                    mode="lines",
                    name="Ideal (linear)",
                    line=dict(dash="dash", color="gray", width=1.5),
                ))
                fig2.update_layout(
                    title="Speedup Curve — Amdahl's Law",
                    xaxis_title="Number of workers",
                    yaxis_title="Speedup (×)",
                    height=350,
                    paper_bgcolor="#0e1117",
                    plot_bgcolor="#0e1117",
                )
                st.plotly_chart(fig2, use_container_width=True)
            else:
                show_img(task_figures("task8_parallelization") / "speedup_curve.png", "Speedup curve")

        # yearly % above threshold — interactive
        df_pct = safe_read(task_tables("task8_parallelization") / "yearly_pct_above_threshold.csv")
        if not df_pct.empty:
            fig3 = px.bar(
                df_pct, x="year", y="pct_above_threshold",
                color_discrete_sequence=["#6c63ff"],
                title="% of variable pairs with |correlation| ≥ 0.6 by year",
                labels={"pct_above_threshold": "% pairs above threshold", "year": "Year"},
            )
            mean_val = df_pct["pct_above_threshold"].mean()
            fig3.add_hline(y=mean_val, line_dash="dash", line_color="red",
                           annotation_text=f"Mean = {mean_val:.1f}%")
            fig3.update_layout(height=350, paper_bgcolor="#0e1117", plot_bgcolor="#0e1117")
            st.plotly_chart(fig3, use_container_width=True)

    with tab2:
        show_img(task_figures("task8_parallelization") / "stable_pairs_table.png",
                 "Stable variable pairs")
        df = safe_read(task_tables("task8_parallelization") / "stable_pairs_table.csv")
        if not df.empty:
            st.dataframe(df.head(15).round(3), use_container_width=True, hide_index=True)
        st.info("NO ↔ NOX stability = 1.00 — strongly correlated in 100% of year/sensor combinations. Confirms chemistry.")

    with tab3:
        target_choice = st.radio("Target pollutant", ["NO2", "NOX"], horizontal=True)
        show_img(task_figures("task8_parallelization") / f"what_drives_{target_choice.lower()}_pollution.png",
                 f"What drives {target_choice}?")

        df_assoc = safe_read(task_tables("task8_parallelization") / "variable_pollution_association.csv")
        if not df_assoc.empty:
            fig4 = px.bar(
                df_assoc.head(15).sort_values("mean_signed_corr_with_pollutants"),
                x="mean_signed_corr_with_pollutants",
                y="variable",
                orientation="h",
                color="mean_signed_corr_with_pollutants",
                color_continuous_scale=["#1f77b4", "white", "#d62728"],
                color_continuous_midpoint=0,
                title="Variables associated with pollution (signed correlation)",
            )
            fig4.update_layout(height=450, paper_bgcolor="#0e1117", plot_bgcolor="#0e1117")
            st.plotly_chart(fig4, use_container_width=True)

    with tab4:
        df = safe_read(task_tables("task8_parallelization") / "stable_strong_correlations.csv")
        if not df.empty:
            st.subheader("Stable strong correlations")
            st.dataframe(df.head(20).round(3), use_container_width=True, hide_index=True)

        df2 = safe_read(task_tables("task8_parallelization") / "runtime_comparison.csv")
        if not df2.empty:
            st.subheader("Runtime summary")
            st.dataframe(df2, use_container_width=True, hide_index=True)


# task 9 — forecasting
elif page == " Task 9 — Forecasting":
    st.title(" Forecasting Model — Task 9")
    st.markdown("Gradient Boosting, XGBoost and Random Forest trained on **weather + traffic features only** (2019–2024). Pollutants excluded to avoid data leakage.")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Best model", "Gradient Boosting", "CV R²=0.54, most stable")
    col2.metric("NO2 R² (test)", "0.67", "RMSE=8.6")
    col3.metric("NOX R² (test)", "0.63", "RMSE=22.1")
    col4.metric("Top feature", "VV — wind speed", "importance ~0.55")

    st.markdown("---")

    tab1, tab2, tab3, tab4 = st.tabs([" Model Comparison", " Predicted vs Actual", " Feature Importance", " Tables"])

    with tab1:
        show_img(task_figures("task9_forecasting") / "model_comparison.png",
                 "R², RMSE and MAE by model and target")

        df_metrics = safe_read(task_tables("task9_forecasting") / "model_test_metrics.csv")
        if not df_metrics.empty:
            metric_choice = st.radio("Metric", ["r2", "rmse", "mae"], horizontal=True)
            fig = px.bar(
                df_metrics,
                x="target", y=metric_choice, color="model",
                barmode="group",
                color_discrete_map={
                    "Gradient Boosting": "#6c63ff",
                    "XGBoost": "#2ecc71",
                    "Random Forest": "#ff6b6b",
                },
                title=f"{metric_choice.upper()} by model and target",
            )
            fig.update_layout(height=380, paper_bgcolor="#0e1117", plot_bgcolor="#0e1117")
            st.plotly_chart(fig, use_container_width=True)

        st.info("GB ≈ XGBoost for NO2 (both R²=0.67). GB > XGBoost for NOX (0.63 vs 0.60). "
                "GB selected based on highest CV R²=0.54 and lowest std=0.05 across folds.")

        st.subheader("Limitations")
        col1, col2 = st.columns(2)
        col1.warning(" Daily aggregation — loses hourly patterns (rush hour averaged out)")
        col1.warning(" 2019–2024 only — weather unavailable before 2019")
        col2.warning(" No lagged features — current day only, no yesterday's wind")
        col2.warning(" Mild overfitting — CV R²=0.54 vs test R²=0.67")

    with tab2:
        target_pred = st.radio("Target", ["NO2", "NOX"], horizontal=True)
        show_img(task_figures("task9_forecasting") / f"predicted_vs_actual_{target_pred.lower()}.png",
                 f"Predicted vs actual — {target_pred} (Gradient Boosting)")
        if target_pred == "NOX":
            st.caption("NOX shows more spread than NO2 — higher natural variability makes it harder to predict.")

    with tab3:
        col1, col2 = st.columns(2)
        with col1:
            target_imp = st.selectbox("Target", ["no2", "nox"])
        with col2:
            model_imp = st.selectbox("Model", ["gradient_boosting", "xgboost", "random_forest"])

        show_img(task_figures("task9_forecasting") / f"importance_{target_imp}_{model_imp}.png",
                 f"Feature importance — {target_imp.upper()} — {model_imp}")

        # interactive plotly feature importance
        df_imp = safe_read(task_tables("task9_forecasting") / "feature_importances.csv")
        if not df_imp.empty:
            model_label_map = {
                "gradient_boosting": "Gradient Boosting",
                "xgboost": "XGBoost",
                "random_forest": "Random Forest",
            }
            sub = df_imp[
                (df_imp["target"].str.upper() == target_imp.upper()) &
                (df_imp["model"] == model_label_map[model_imp])
            ].sort_values("importance", ascending=True).tail(12)

            if not sub.empty:
                fig = px.bar(
                    sub,
                    x="importance", y="feature",
                    orientation="h",
                    color="importance",
                    color_continuous_scale="Purples",
                    title=f"Top features — {target_imp.upper()} — {model_label_map[model_imp]}",
                )
                fig.update_layout(height=420, paper_bgcolor="#0e1117", plot_bgcolor="#0e1117")
                st.plotly_chart(fig, use_container_width=True)

    with tab4:
        df_metrics = safe_read(task_tables("task9_forecasting") / "model_test_metrics.csv")
        if not df_metrics.empty:
            st.subheader("Test set metrics")
            st.dataframe(df_metrics.round(4), use_container_width=True, hide_index=True)

        df_cv = safe_read(task_tables("task9_forecasting") / "model_cv_summary.csv")
        if not df_cv.empty:
            st.subheader("Cross-validation summary")
            st.dataframe(df_cv.round(4), use_container_width=True, hide_index=True)
            st.caption("CV R² used for model selection — more reliable than single test split.")


#  task 10 — final visualization
elif page == " Task 10 — Final Visualization":
    st.title(" Task 10 — Final Visualization")
    st.markdown("**Goal:** Communicate key findings through clear visualizations.")
    st.markdown("---")
 
    task_choice = st.radio(
        "Select task",
        ["Task 1", "Task 2", "Task 3", "Task 4", "Task 5", "Task 6", "Task 8", "Task 9"],
        horizontal=True
    )
 
    st.markdown("---")
 
    # task 1
    if task_choice == "Task 1":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Variable type counts",
                "Interpolation rate",
                "NO monthly time series",
                "NO value distribution",
            ], horizontal=True)
            fname_map = {
                "Variable type counts": "variable_type_counts.png",
                "Interpolation rate": "interpolation_rate_by_variable_type.png",
                "NO monthly time series": "NO_monthly_timeseries.png",
                "NO value distribution": "NO_value_distribution.png",
            }
            show_img(task_figures("task1_load_inspect") / fname_map[fig_choice], fig_choice)
        with tab2:
            table_choice = st.radio("Table", [
                "variable_type_counts",
                "date_range_summary",
                "interpolation_by_variable_type",
            ], horizontal=True)
            df = safe_read(task_tables("task1_load_inspect") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df, use_container_width=True, hide_index=True)
 
    # task 2
    elif task_choice == "Task 2":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Data quality dashboard",
                "Data availability matrix",
                "Missingness over time",
                "Gap length distribution",
                "Sensor × pollutant heatmap",
            ], horizontal=True)
            fname_map = {
                "Data quality dashboard": "data_quality_dashboard.png",
                "Data availability matrix": "data_availability_matrix.png",
                "Missingness over time": "missingness_by_year_type_stacked.png",
                "Gap length distribution": "gap_length_distribution.png",
                "Sensor × pollutant heatmap": "missingness_heatmap_sensor_variable.png",
            }
            show_img(task_figures("task2_missingness") / fname_map[fig_choice], fig_choice)
        with tab2:
            table_choice = st.radio("Table", [
                "original_missingness_by_variable_type",
                "original_missingness_by_pollutant",
                "original_missingness_by_sensor",
                "invalid_values_summary",
            ], horizontal=True)
            df = safe_read(task_tables("task2_missingness") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df, use_container_width=True, hide_index=True)
 
    # task 3
    elif task_choice == "Task 3":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Method ranking",
                "Comparison panel",
                "Distribution overlay",
            ], horizontal=True)
            if fig_choice == "Method ranking":
                show_img(task_figures("task3_imputation") / "imputation_method_ranking.png", "Method ranking")
            elif fig_choice == "Comparison panel":
                show_img(task_figures("task3_imputation") / "imputation_method_comparison_panel.png", "Comparison panel")
            else:
                pollutant = st.selectbox("Pollutant", ["NO2", "NOX", "NO", "O3", "CO", "SO2", "PM10", "PM2_5"])
                show_img(task_figures("task3_imputation") / f"distribution_overlay_pollutant_{pollutant}.png", pollutant)
        with tab2:
            df = safe_read(task_tables("task3_imputation") / "imputation_error_summary.csv")
            if not df.empty:
                st.dataframe(df.round(3), use_container_width=True, hide_index=True)
 
    # task 4
    elif task_choice == "Task 4":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Yearly trends",
                "Long-term with COVID",
                "NO2 vs O3 anticorrelation",
                "Mann-Kendall",
                "Hourly cycle",
                "Weekday cycle",
                "Seasonal cycle",
                "ACF lag-12",
                "Station-year heatmap",
            ], horizontal=True)
            fname_map = {
                "Yearly trends": "yearly_pollution_trends.png",
                "Long-term with COVID": "longterm_trend_covid_annotated.png",
                "NO2 vs O3 anticorrelation": "no2_o3_anticorrelation_seasonal.png",
                "Mann-Kendall": "mann_kendall_trend_by_pollutant.png",
                "Hourly cycle": "hourly_pollution_cycle.png",
                "Weekday cycle": "weekday_pollution_cycle.png",
                "Seasonal cycle": "seasonal_pollution_cycle.png",
                "ACF lag-12": "acf_lag12_by_pollutant.png",
                "Station-year heatmap": "station_year_heatmap_NO.png",
            }
            show_img(task_figures("task4_temporal") / fname_map[fig_choice], fig_choice)
        with tab2:
            table_choice = st.radio("Table", [
                "mann_kendall_trend_summary",
                "temporal_interpretation_summary",
                "cycle_strength_summary",
                "acf_lag12_summary",
            ], horizontal=True)
            df = safe_read(task_tables("task4_temporal") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df.round(4), use_container_width=True, hide_index=True)
 
    # task 5
    elif task_choice == "Task 5":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            col1, col2 = st.columns(2)
            with col1:
                graph_type = st.radio("Method", ["KNN", "Distance threshold"], horizontal=True)
            with col2:
                if graph_type == "KNN":
                    k_val = st.select_slider("k", options=[2, 3, 4, 5], value=2)
                    graph_key = f"knn_k{k_val}"
                else:
                    dist_val = st.select_slider("Threshold", options=["3024m", "4709m", "7517m", "10452m"])
                    graph_key = f"threshold_{dist_val}"
 
            fig_type = st.radio("Figure type", ["Community & betweenness", "Pollution & eigenvector", "Centrality ranking"], horizontal=True)
            fname_map = {
                "Community & betweenness": f"spatial_network_{graph_key}_community_centrality.png",
                "Pollution & eigenvector": f"spatial_network_{graph_key}_pollution_eigenvector.png",
                "Centrality ranking": f"centrality_ranking_{graph_key}.png",
            }
            show_img(task_figures("task5_spatial_network") / fname_map[fig_type], fig_type)
 
            metric = st.radio("Comparison metric", ["density", "average_degree", "n_connected_components"], horizontal=True)
            show_img(task_figures("task5_spatial_network") / f"network_{metric}_comparison.png", metric)
 
        with tab2:
            table_choice = st.radio("Table", [
                "selected_spatial_node_centrality",
                "selected_spatial_graph_summary",
                "spatial_graph_summary",
            ], horizontal=True)
            df = safe_read(task_tables("task5_spatial_network") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df.round(4), use_container_width=True, hide_index=True)
 
    # task 6
    elif task_choice == "Task 6":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Correlation network",
                "Joint overlay",
                "Community Jaccard",
                "Centrality ranking",
            ], horizontal=True)
 
            if fig_choice == "Correlation network":
                col1, col2 = st.columns(2)
                with col1:
                    pollutant = st.selectbox("Pollutant", ["NO2", "NO", "NOX", "O3", "<PM10"])
                with col2:
                    threshold = st.select_slider("Threshold", options=[0.50, 0.60, 0.70, 0.80, 0.90])
                show_img(task_figures("task6_correlation_network") / f"correlation_network_{pollutant}_corr_{threshold:.2f}.png",
                         f"{pollutant} at r≥{threshold}")
            elif fig_choice == "Joint overlay":
                show_img(task_figures("task6_correlation_network") / "joint_spatial_correlation_overlay.png", "Joint overlay")
            elif fig_choice == "Community Jaccard":
                show_img(task_figures("task6_correlation_network") / "community_jaccard_similarity.png", "Community agreement")
            else:
                pollutant = st.selectbox("Pollutant", ["NO2", "NO", "NOX", "O3", "<PM10"])
                show_img(task_figures("task6_correlation_network") / f"centrality_ranking_{pollutant}_corr_0.50.png",
                         f"Centrality — {pollutant}")
 
        with tab2:
            table_choice = st.radio("Table", [
                "correlation_network_comparison_all_pollutants",
                "joint_network_overlay_summary",
                "community_jaccard_similarity",
            ], horizontal=True)
            df = safe_read(task_tables("task6_correlation_network") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df.round(4), use_container_width=True, hide_index=True)
 
    # task 8
    elif task_choice == "Task 8":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Runtime comparison",
                "Speedup curve",
                "Stable pairs",
                "What drives NO2",
                "What drives NOX",
                "Yearly % above threshold",
                "Stable strong correlations",
            ], horizontal=True)
            fname_map = {
                "Runtime comparison": "runtime_comparison.png",
                "Speedup curve": "speedup_curve.png",
                "Stable pairs": "stable_pairs_table.png",
                "What drives NO2": "what_drives_no2_pollution.png",
                "What drives NOX": "what_drives_nox_pollution.png",
                "Yearly % above threshold": "yearly_pct_above_threshold.png",
                "Stable strong correlations": "stable_strong_correlations.png",
            }
            show_img(task_figures("task8_parallelization") / fname_map[fig_choice], fig_choice)
        with tab2:
            table_choice = st.radio("Table", [
                "runtime_comparison",
                "stable_pairs_table",
                "variable_pollution_association",
                "stable_strong_correlations",
                "yearly_pct_above_threshold",
            ], horizontal=True)
            df = safe_read(task_tables("task8_parallelization") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df.round(3), use_container_width=True, hide_index=True)
 
    # task 9
    elif task_choice == "Task 9":
        tab1, tab2 = st.tabs([" Figures", " Tables"])
        with tab1:
            fig_choice = st.radio("Figure", [
                "Model comparison",
                "Predicted vs actual",
                "Feature importance",
            ], horizontal=True)
 
            if fig_choice == "Model comparison":
                show_img(task_figures("task9_forecasting") / "model_comparison.png", "Model comparison")
            elif fig_choice == "Predicted vs actual":
                target = st.radio("Target", ["NO2", "NOX"], horizontal=True)
                show_img(task_figures("task9_forecasting") / f"predicted_vs_actual_{target.lower()}.png",
                         f"Predicted vs actual — {target}")
            else:
                col1, col2 = st.columns(2)
                with col1:
                    target_imp = st.selectbox("Target", ["no2", "nox"])
                with col2:
                    model_imp = st.selectbox("Model", ["gradient_boosting", "xgboost", "random_forest"])
                show_img(task_figures("task9_forecasting") / f"importance_{target_imp}_{model_imp}.png",
                         f"Feature importance — {target_imp.upper()} — {model_imp}")
 
        with tab2:
            table_choice = st.radio("Table", [
                "model_test_metrics",
                "model_cv_summary",
                "feature_importances",
            ], horizontal=True)
            df = safe_read(task_tables("task9_forecasting") / f"{table_choice}.csv")
            if not df.empty:
                st.dataframe(df.round(4), use_container_width=True, hide_index=True)
 